---
title: "HW8"
author: "Charles Zhang"
output: 
  html_document:
    keep_md: yes
---
## Activity A14: Introduction to Scraping

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest) 
library(robotstxt) 
```

**Exercise 1.1** Find the correct selectors for the following fields. Make sure that each matches 762 results:

1. Course Number
2. Course Name
3. Day
4. Time
5. Room
6. Instructor
7. Avail. / Max
8. General Education Requirements (make sure you only match 762; beware of the Mac copyright banner at the bottom of the page!)
9. Description
Then, put all this information into one data frame. Do not include any extraneous information like “Instructor:”.

**Exercise 1.2** Create a chart that shows the number of sections offered per department. Hint: The department is a substring of the course number. Yes, COMP and MATH are the same department, but for this exercise you can just show the results by four letter department code, e.g., with COMP and MATH separate.

**Exercise 1.3** Analyze the typical length of course names by department. To do so, create a dplyr pipeline that creates a new data table based on your courses data table, with the following changes:

1. New columns for the length of the title of a course and the length of the description of the course. Hint: str_length.
2. Remove departments that have fewer than 10 sections of courses. To do so, group by department, then remove observations in groups with fewer than 10 sections (Hint: use filter with n()). Then ungroup the data.
3. Create a visualization of the differences across groups in lengths of course names or course descriptions. Think carefully about the visualization you should be using!
